# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

remote_write:
- url: http://cortex:9009/api/prom/push

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'test-exporter'
    static_configs:
    - targets: ['test-exporter:80']
  - job_name: 'cortex'
    static_configs:
    - targets: ['cortex:9009']