# config file version
apiVersion: 1

deleteDatasources:
  - name: cortex
    orgId: 1

datasources:
- name: cortex
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: true
  version: 1
  editable: false