#
# Starts the latest cortex/grafana/prometheus/jaeger stack.  After running check:
#  grafana:    http://localhost:3000
#  cortex:     http://localhost:9009
#  prometheus: http://localhost:9090
#  jaeger:     http://localhost:16686
#
version: "3.5"
services:
  cortex:
    image: quay.io/cortexproject/cortex:v1.9.0
    volumes:
    - ./config/single_process_cortex.yaml:/etc/config/single_process_cortex.yaml
    entrypoint:
    - /bin/cortex
    - -config.file=/etc/config/single_process_cortex.yaml
    ports:
    - "9009:9009"

  grafana:
    image: grafana/grafana-enterprise:latest
    volumes:
    - ./datasource/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    ports:
    - "3000:3000"
    # extra_hosts:
    # - "cortex:<host ip>"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin

  agent:
    image: grafana/agent:latest
    volumes:
      - ./config/agent.yaml:/etc/agent-config/agent.yaml
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
      REMOTE_WRITE_HOST: cortex:9009
    ports:
      - "12345:12345"

  dummy-exporter:
    image: kobtea/dummy_exporter
    volumes:
    - ./config/dummy_exporter.yml:/etc/agent-config/dummy_exporter.yml
    ports:
      - "9510:9510"